window.TREE_DATA = [
    {'Taxon': 'Araucaria araucana', 'French': 'Araucaria', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Picea abies', 'French': 'Epicéa', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Taxus baccata', 'French': 'If', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Pseudotsuga menziesii', 'French': 'Sapin de Douglas', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Albies alba', 'French': 'Sapin pectiné', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Cedrus atlantica', 'French': 'Cèdre bleu de l’Atlas', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Latrix decidua', 'French': 'Mélèze', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Pinus pinaster', 'French': 'Pin des landes', 'French2': 'Pin maritime', 'French3': 'None'},
    {'Taxon': 'Pinus nigra', 'French': 'Pin noir', 'French2': 'Pin d’Autriche', 'French3': 'None'},
    {'Taxon': 'Pinus pinea', 'French': 'Pin parasol', 'French2': 'Pin pignon', 'French3': 'None'},
    {'Taxon': 'Pinus sylvestris', 'French': 'Pin sylvestre', 'French2': 'Pin du Nord', 'French3': 'Pin d’Ecosse'},
    {'Taxon': 'Cupressus sempervirens', 'French': 'Cyprès commun', 'French2': 'Cyprès d’Italie', 'French3': 'None'},
    {'Taxon': 'Sequoiadendron giganteum', 'French': 'Sequoia géant', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Ginkgo biloba', 'French': 'Gingko', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Cercis siliquastrum', 'French': 'Arbre de Judée', 'French2': 'Gainier', 'French3': 'None'},
    {'Taxon': 'Alnus glutinosa', 'French': 'Aulne glutineux', 'French2': 'Aulne noir', 'French3': 'None'},
    {'Taxon': 'Catalpa bignonioides', 'French': 'Catalpa', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Morus nigra', 'French': 'Mûrier noir', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Corylus avellana', 'French': 'Noisetier', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Tilia platyphyllos', 'French': 'Tilleul à grandes feuilles', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Tilia cordata', 'French': 'Tilleul à petites feuilles', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Populus tremula', 'French': 'Tremble', 'French2': ' Peuplier tremble', 'French3': 'None'},
    {'Taxon': 'Betula pendula', 'French': 'Bouleau verruqueux', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Syringa vulgaris', 'French': 'Lilas', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Populus nigra', 'French': 'Peuplier noir', 'French2': ' Liard', 'French3': ' Bioulasse'},
    {'Taxon': 'Sorbus aria', 'French': 'Alisier blanc', 'French2': ' Alouchier', 'French3': ' Sorbier des Alpes'},
    {'Taxon': 'Arbutus unedo', 'French': 'Arbousier', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Castanea sativa', 'French': 'Châtaignier', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Carpinus betulus', 'French': 'Charme', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Quercus ilex', 'French': 'Chêne vert', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Ilex aquifolium', 'French': 'Houx', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Prunus avium', 'French': 'Merisier', 'French2': 'Cerisier des oiseaux', 'French3': 'None'},
    {'Taxon': 'Celtis australis', 'French': 'Micocoulier de Provence', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Ulmus minor', 'French': 'Orme', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Pyrus communis', 'French': 'Poirier', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Malus sylvestris', 'French': 'Pommier sauvage', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Prunus spinosa', 'French': 'Prunellier', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Prunus domestica', 'French': 'Prunier', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Salix caprea', 'French': 'Saule marsault', 'French2': 'Saule des chèvres', 'French3': 'None'},
    {'Taxon': 'Buxus sempervirens', 'French': 'Buis', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Cydonia oblonga', 'French': 'Cognassier', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Cornus sanguinea', 'French': 'Cornouiller sanguin', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Fagus sylvatica', 'French': 'Hêtre', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Laurus nobilis', 'French': 'Laurier-sauce', 'French2': 'Laurier vrai', 'French3': 'Laurier noble'},
    {'Taxon': 'Magnolia grandiflora', 'French': 'Magnolia', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Mespilus germanica', 'French': 'Néflier', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Hippophae rhamnoides', 'French': 'Argousier', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Eucalyptus globulus', 'French': 'Eucalyptus', 'French2': 'Gommier bleu', 'French3': 'None'},
    {'Taxon': 'Olea europea', 'French': 'Olivier', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Salix alba', 'French': 'Saule blanc', 'French2': 'Osier blanc', 'French3': 'None'},
    {'Taxon': 'Salix babylonica', 'French': 'Saule pleureur', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Ailanthus altissima', 'French': 'Ailante', 'French2': 'None', 'French3': 'None'}
    , {'Taxon': 'Sorbus domestica', 'French': 'Cormier', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Fraximus excelsior', 'French': 'Frêne', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Aesculus hippocastanum', 'French': 'Marronnier d’Inde', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Juglans regia', 'French': 'Noyer', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Robinia pseudoacacia', 'French': 'Robinier', 'French2': 'Faux acacia', 'French3': 'None'},
    {'Taxon': 'Sorbus aucuparia', 'French': 'Sorbier des oiseleurs', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Sambucus nigra', 'French': 'Sureau noir', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Quercus robur', 'French': 'Chêne pédonculé', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Quercus pubescens', 'French': 'Chêne pubescent', 'French2': 'Chêne blanc', 'French3': 'None'},
    {'Taxon': 'Quercus petraea', 'French': 'Chêne sessile', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Sorbus torminalis', 'French': 'Alisier torminal', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Crataegus monogyna', 'French': 'Aubépine', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Acer campestre', 'French': 'Érable champêtre', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Acer platanoides', 'French': 'Érable plane', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Acer pseudoplatanus', 'French': 'Erable sycomore', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Ficus carica', 'French': 'Figuier', 'French2': 'None', 'French3': 'None'},
    {'Taxon': 'Populus alba', 'French': 'Peuplier blanc', 'French2': 'Peuplier de Hollande', 'French3': 'None'},
    {'Taxon': 'Platanus x hispanica', 'French': 'Platane commun', 'French2': 'None', 'French3': 'None'}];